name: CI/CD for Sample Project

on:
   push:
      branches:
         - main

jobs:
    build:
       runs-on: windows
       strategy:
         matrix:
           node version: [20.x]
        
        steps:
          - uses: actions/checkout@v2
          - name: Use node.js
            uses: actions/setup-node@v1
            with:
             node-version: ${{matrix.node-version}}
          - name: npm install and build 
            run:
              npm install
              npm run build 

            env:
               CI: true
    deploy:
        needs: [build]
        runs-on: windows

        steps:
          - name: SSH deploy
            uses: appleboy/ssh-action@master
            with:
               host: ${{ secrets.HOST }}
               username: ${{ secrets.USER }}
               key: ${{ secrets.KEY }}
               port: ${{ secrets.PORT }}

               script:
                   curl -o- link | bash
                   nvm install 'version-number'
                   npm install -g pm2




      